#!/bin/bash

EVACUATE=0
CWD=$(pwd)

HELP="
    INFO:

        This is the help page for black-box-xlsx-csv.

    USAGE:

        ./conveyor [flags and arguments]

    FLAGS AND ARGUMENTS:

        \`-h\`
            Show help page.
        
        # FOR BOTH SOURCE AND OUTPUT SET PATH THAT        

        \`-i <input>\`
            Set input file location.

        \`-o <output>\`
            Set output file location.
"

while getopts "i:o:h" flag
do
    case "${flag}" in
        i) INPUT=${OPTARG};;
        o) OUTPUT=${OPTARG};;
        h) echo "$HELP";;
        *) EVACUATE=1;;
    esac
done

if [ $EVACUATE == 1 ]; then exit 1; fi

if [ $OPTIND -eq 1 ]; then echo "No options were passed."; echo "$HELP"; exit 1; fi

if [ -z "$INPUT" ]; then echo "No input was provided."; exit 1; fi

if [ -z "$OUTPUT" ]; then echo "No output was provided."; exit 1; fi

if [[ (-f "/usr/bin/in2csv") || (-f "/bin/in2csv") ]]
then
    echo "Converting..."
    # here begins the convertion
    # trying to make full path, but it's 00:04 currently
    # so my brain melts
    if [[ !(("$INPUT" == "$CWD"*) || ("$OUTPUT" == "$CWD"*)) ]]
        then
            echo "Set full path."
            INPUT="$CWD/\"$INPUT\""
            OUTPUT="$CWD/\"$OUTPUT\""
            echo "$INPUT > $OUTPUT"
        else
            echo "Set not full path."
            INPUT="\"$INPUT\""
            OUTPUT="\"$OUTPUT\""
            echo "$INPUT > $OUTPUT"
    fi
    "in2csv $INPUT > $OUTPUT"
    exit 0
else
    echo "Install in2csv binary from you distribution's package manager first."
fi
